# Generated by Django 6.0 on 2025-12-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0005_alter_product_wattage'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_configurations', to='projects.area')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.driver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.driver')),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_driver', to='configurations.lightingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.accessory')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.lightingconfiguration')),
            ],
        ),
    ]
