# Generated by Django 5.2.10 on 2026-02-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='projects.area')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='projects.subarea')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.driver')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_drivers', to='configurations.lightingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.accessory')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='configurations.lightingconfiguration')),
            ],
        ),
        migrations.AddIndex(
            model_name='lightingconfiguration',
            index=models.Index(fields=['project', 'area', 'is_active'], name='configurati_project_be4c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='lightingconfiguration',
            index=models.Index(fields=['project', 'area', 'configuration_version'], name='configurati_project_17bcdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lightingconfiguration',
            unique_together={('project', 'area', 'configuration_version', 'product')},
        ),
    ]
