# Generated by Django 5.2.10 on 2026-02-03 05:19

import apps.projects.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('location_metadata', models.JSONField(blank=True, default=apps.projects.models.default_location_metadata)),
                ('status', models.CharField(choices=[('INQUIRY', 'Inquiry'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='INQUIRY', max_length=20)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('refered_by', models.CharField(blank=True, null=True)),
                ('segment_area', models.CharField(choices=[('MASTER PLANNING', 'Master Planning'), ('COMMERCIAL', 'Commercial'), ('PRIVATE RESIDENCE', 'Private Residence'), ('RESIDENTIAL TOWNSHIP', 'Residential Township'), ('LANDSCAPE', 'Landscape'), ('FACADE', 'Facade'), ('HOSPITALITY', 'Hospitality'), ('HEALTH CARE', 'Health Care'), ('PUBLIC SPACE', 'Public Space'), ('SEZ', 'Sez'), ('SPECIAL/OTHERS', 'Special/Others'), ('INDUSTRIAL', 'Industrial'), ('RETAIL', 'Retail'), ('INFRASTRUCTURE', 'Infrastructure'), ('INSTITUTIONS', 'Instituions'), ('MEMORIALS', 'Memorials'), ('MALL/MULTIPLEX', 'Mall/Multiplex'), ('CLUB HOUSE', 'Club House'), ('TEMPLE/GURUDWARA/CHURCH', 'Temple/Gurudwara/Church')], default='MASTER PLANNING', max_length=100)),
                ('expecetd_mhr', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100000)])),
                ('fee', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_details', models.JSONField(blank=True, default=apps.projects.models.default_area_details)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('tags', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subarea_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='projects.area')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('area', 'name')},
            },
        ),
    ]
