# Generated by Django 5.2.10 on 2026-02-17 09:53

import apps.masters.models.accessory
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=100)),
                ('accessory_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('compatible_mounting_styles', models.JSONField(default=list, help_text='Allowed values: SURFACE, RECESSED, INGROUND, TRACK MOUNTED', validators=[apps.masters.models.accessory.validate_mounting_styles])),
                ('min_diameter_mm', models.IntegerField(blank=True, null=True)),
                ('max_diameter_mm', models.IntegerField(blank=True, null=True)),
                ('compatible_ip_class', models.IntegerField(blank=True, null=True)),
                ('accessory_category', models.CharField(choices=[('MOUNTING', 'Mounting'), ('OPTICAL', 'Optical'), ('DECORATIVE', 'Decorative'), ('INSTALLATION', 'Installation')], max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, default=5, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=100, unique=True)),
                ('driver_make', models.CharField(max_length=100)),
                ('input_voltage_min', models.IntegerField(blank=True, null=True)),
                ('input_voltage_max', models.IntegerField(blank=True, null=True)),
                ('max_wattage', models.IntegerField(blank=True, null=True)),
                ('dimmable', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
                ('output_current_ma', models.IntegerField(blank=True, null=True)),
                ('output_voltage_min', models.IntegerField(blank=True, null=True)),
                ('output_voltage_max', models.IntegerField(blank=True, null=True)),
                ('constant_type', models.CharField(choices=[('CC', 'Constant Current'), ('CV', 'Constant Voltage')], default='CC', max_length=20)),
                ('dimming_protocol', models.CharField(choices=[('NONE', 'Non Dimmable'), ('DALI', 'DALI'), ('0-10V', '0-10V'), ('1-10V', '1-10V'), ('TRIAC', 'TRIAC')], default='NONE', max_length=20)),
                ('ip_class', models.IntegerField(blank=True, null=True)),
                ('warranty_years', models.IntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('order_code', models.CharField(max_length=100, null=True)),
                ('luminaire_color_ral', models.CharField(blank=True, max_length=100, null=True)),
                ('characteristics', models.TextField(blank=True, null=True)),
                ('diameter_mm', models.IntegerField(blank=True, null=True)),
                ('length_mm', models.IntegerField(blank=True, null=True)),
                ('width_mm', models.IntegerField(blank=True, null=True)),
                ('height_mm', models.IntegerField(blank=True, null=True)),
                ('mounting_style', models.CharField(blank=True, choices=[('SURFACE', 'Surface Mounted'), ('RECESSED', 'Recessed'), ('INGROUND', 'Inground Mounted'), ('TRACK MOUNTED', 'Track Mounted')], default='SURFACE', max_length=15, null=True)),
                ('beam_angle_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_class', models.IntegerField(blank=True, null=True)),
                ('wattage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('op_voltage', models.IntegerField(blank=True, null=True)),
                ('op_current', models.IntegerField(blank=True, null=True)),
                ('lumen_output', models.IntegerField(blank=True, null=True)),
                ('cct_kelvin', models.IntegerField(blank=True, null=True)),
                ('cri_cci', models.IntegerField(blank=True, null=True)),
                ('lumen_efficency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('warranty_years', models.IntegerField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('visual_image', models.ImageField(blank=True, null=True, upload_to='lighting_specs/images/')),
                ('illustrative_details', models.ImageField(blank=True, null=True, upload_to='lighting_specs/images/')),
                ('photometrics', models.ImageField(blank=True, null=True, upload_to='lighting_specs/images/')),
                ('base_price', models.DecimalField(decimal_places=2, default=7, max_digits=10)),
                ('driver_integration', models.CharField(choices=[('INTEGRATED', 'Integrated Driver'), ('EXTERNAL', 'External Driver')], default='EXTERNAL', max_length=15)),
                ('cutout_diameter_mm', models.IntegerField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], default='INDOOR', max_length=20)),
                ('control_ready', models.CharField(choices=[('NONE', 'None'), ('DALI', 'DALI'), ('0-10V', '0-10V')], default='NONE', max_length=20)),
                ('electrical_type', models.CharField(choices=[('CC', 'Constant Current'), ('CV', 'Constant Voltage')], default='CC', max_length=2)),
            ],
        ),
    ]
