# Generated by Django 6.0 on 2026-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=100)),
                ('accessory_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=36, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=100, unique=True)),
                ('driver_make', models.CharField(max_length=100)),
                ('driver_type', models.CharField(max_length=50)),
                ('input_voltage_range', models.CharField(blank=True, max_length=100, null=True)),
                ('max_wattage', models.IntegerField(blank=True, null=True)),
                ('dimmable', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
                ('base_price', models.DecimalField(decimal_places=2, default=55, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('order_code', models.CharField(max_length=100, unique=True)),
                ('luminaire_color_ral', models.CharField(blank=True, max_length=100, null=True)),
                ('characteristics', models.TextField(blank=True, null=True)),
                ('diameter_mm', models.IntegerField(blank=True, null=True)),
                ('length_mm', models.IntegerField(blank=True, null=True)),
                ('width_mm', models.IntegerField(blank=True, null=True)),
                ('height_mm', models.IntegerField(blank=True, null=True)),
                ('mounting_style', models.CharField(blank=True, choices=[('SURFACE', 'Surface Mounted'), ('RECESSED', 'Recessed'), ('INGROUND', 'Inground Mounted'), ('TRACK MOUNTED', 'Track Mounted')], default='SURFACE', max_length=15, null=True)),
                ('beam_angle_degree', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ip_class', models.IntegerField(blank=True, null=True)),
                ('wattage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('op_voltage', models.IntegerField(blank=True, null=True)),
                ('op_current', models.IntegerField(blank=True, null=True)),
                ('lumen_output', models.IntegerField(blank=True, null=True)),
                ('cct_kelvin', models.IntegerField(blank=True, null=True)),
                ('cri_cci', models.IntegerField(blank=True, null=True)),
                ('lumen_efficency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('warranty_years', models.IntegerField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('visual_image', models.ImageField(blank=True, null=True, upload_to='lighting_specs/images/')),
                ('base_price', models.DecimalField(decimal_places=2, default=64, max_digits=10)),
                ('driver_integration', models.CharField(choices=[('INTEGRATED', 'Integrated Driver'), ('EXTERNAL', 'External Driver')], default='EXTERNAL', max_length=15)),
            ],
        ),
    ]
