# Generated by Django 6.0 on 2025-12-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lumen_efficency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mounting_style',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
