# Generated by Django 6.0 on 2025-12-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_product_lumen_efficency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mounting_style',
            field=models.CharField(blank=True, choices=[('SURFACE', 'Surface Mount'), ('RECESSED', 'Recessed Mount'), ('INGROUND', 'Inground Mount'), ('TRACK MOUNTED', 'Track Mounted')], max_length=15, null=True),
        ),
    ]
