# Generated by Django 6.0 on 2025-12-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_product_mounting_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mounting_style',
            field=models.CharField(blank=True, choices=[('SURFACE', 'Surface Mounted'), ('RECESSED', 'Recessed'), ('INGROUND', 'Inground Mounted'), ('TRACK MOUNTED', 'Track Mounted')], default='SURFACE', max_length=15, null=True),
        ),
    ]
