# Generated by Django 6.0 on 2025-12-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_product_mounting_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wattage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
