# Generated by Django 5.2.10 on 2026-02-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Log Entries',
            },
        ),
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMMERCIAL_APPROVED', 'Commercial Approved'), ('FINAL', 'Final')], default='DRAFT', max_length=20)),
                ('source_configuration_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('DRIVER', 'Driver'), ('ACCESSORY', 'Accessory')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('markup_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.accessory')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='projects.area')),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boq.boq')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.driver')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='boq',
            index=models.Index(fields=['project', 'source_configuration_version'], name='boq_boq_project_dc87c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boq',
            unique_together={('project', 'version')},
        ),
        migrations.AddConstraint(
            model_name='boqitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'PRODUCT'), ('product__isnull', False)), models.Q(('driver__isnull', False), ('item_type', 'DRIVER')), models.Q(('accessory__isnull', False), ('item_type', 'ACCESSORY')), _connector='OR'), name='boq_item_type_reference_check'),
        ),
        migrations.AddConstraint(
            model_name='boqitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'PRODUCT')), fields=('boq', 'area', 'product'), name='uniq_product_per_area_per_boq'),
        ),
    ]
