# Generated by Django 6.0 on 2025-12-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('DRIVER', 'Driver'), ('ACCESSORY', 'Accessory')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.accessory')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.area')),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boq.boq')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.driver')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'PRODUCT'), ('product__isnull', False)), models.Q(('driver__isnull', False), ('item_type', 'DRIVER')), models.Q(('accessory__isnull', False), ('item_type', 'ACCESSORY')), _connector='OR'), name='boq_item_type_reference_check')],
            },
        ),
    ]
